print "Starting maya loading and fbx conversion \n";
	
if (`file -q -exists "/Users/jasonisrael/oculusvrscene/60415scene/Assets/test.mb"`)
{		
	file -o "/Users/jasonisrael/oculusvrscene/60415scene/Assets/test.mb";
	FBXExportEmbeddedTextures -v false;
	// FBXExportHardEdges -v true;
	FBXExportApplyConstantKeyReducer -v false;
	FBXExportShowUI -v false;

	print "Before fbx export\n";
	FBXExport -f "/Users/jasonisrael/oculusvrscene/60415scene/Temp/ExportedFBXFile.fbx";
	print "after fbx export\n";
}
else
	print "Could not open Maya file.";


system ("rm \"/Users/jasonisrael/oculusvrscene/60415scene/Temp/CommandPipe\"");

$donepipeKill = `fopen "/Users/jasonisrael/oculusvrscene/60415scene/Temp/SyncPipeKill" "w"`;
fwrite $donepipeKill "Done";
fclose $donepipeKill;
